[OGUI-1018] Tackle grep failure

diff --git a/.github/workflows/gui-checks.yml b/.github/workflows/gui-checks.yml
--- a/.github/workflows/gui-checks.yml
+++ b/.github/workflows/gui-checks.yml
@@ -10,8 +10,8 @@ on:
 env:
   LIST_OF_VARIABLES: \[-dcs_enabled:-\]\|\[-trg_enabled:-\]\|\[-epn_enabled:-\]\|\[-odc_topology:-\]\|\[-odc_enabled:-\]\|\[-qcdd_enabled:-\]\|\[-dd_enabled:-\]\|\[-ddsched_enabled:-\]\|\[-minimal_dpl_enabled:-\]\|\[-readout_cfg_uri:-\]\|\[-qc_config_uri:-\]
 jobs:
-  workflows-directory-check:
-    name: Checks no changes are done to fix variables in workflow directory
+  directories-check:
+    name: Checks no changes are done to fix variables in workflows/tasks directory
     runs-on: macOS-latest
     env:
       RESULT_WORKFLOWS: ''
@@ -27,15 +27,16 @@ jobs:
         working-directory: ./ControlWorkflows
         run: |
           git diff $GITHUB_BASE_REF $GITHUB_HEAD_REF -U0 --word-diff > workflow_changes.txt
-          echo "$(<workflow_changes.txt )"
-          echo "CHANGES_ABOVE"
-          RESULT_WORKFLOWS=$(grep "${{env.LIST_OF_VARIABLES}}" workflow_changes.txt)
-          echo $RESULT_WORKFLOWS
-          echo "RESULT_CHANGES_ABOVE"
+          RESULT_WORKFLOWS=$(grep "${{env.LIST_OF_VARIABLES}}" workflow_changes.txt) || true 
+          # grep command returns exit code != 0 if it fails to find a match, thus we use || true
           if [ -z "$RESULT_WORKFLOWS" ];
           then
             echo "WORKFLOWS folder did not find any breaking changes"
           else 
+            echo "------------------"
+            echo "Identified keys that were changed:"
+            echo $RESULT_WORKFLOWS
+            echo "------------------"
             echo "WORKFLOWS folder found breaking changes. Please inform GUI Developer"
             exit 1
           fi
